name: needs-workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: echo-by-job1
      run: echo "job11111 done"
  
  job2:
    runs-on: ubuntu-latest
    needs: [job1]  
    steps:
    - name: echo-by-job2
      run: echo "job2 done"

  job3:
    runs-on: ubuntu-latest
    steps:
    - name: echo-by-job3
      run: |
        echo "job3 done"
        exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
    - name: echo-by-job4
      run: echo "job 4 done"
